// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkD2nHptUBDDcvQI1phG0MSXE-zndESRc',
    appId: '1:888433101003:web:cd62a36596ba4bba8a734e',
    messagingSenderId: '888433101003',
    projectId: 'employee-60bb8',
    authDomain: 'employee-60bb8.firebaseapp.com',
    storageBucket: 'employee-60bb8.appspot.com',
    measurementId: 'G-NBXKMVFX6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8DxVGDSw7Mp4KFl_Zu3NjGCWYzVdm3dU',
    appId: '1:888433101003:android:0a71362bcc77a8c78a734e',
    messagingSenderId: '888433101003',
    projectId: 'employee-60bb8',
    storageBucket: 'employee-60bb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYi4MnWM_qYsQxNGIgxrnhw9K59YMoBqs',
    appId: '1:888433101003:ios:07ce26126ee37e2d8a734e',
    messagingSenderId: '888433101003',
    projectId: 'employee-60bb8',
    storageBucket: 'employee-60bb8.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYi4MnWM_qYsQxNGIgxrnhw9K59YMoBqs',
    appId: '1:888433101003:ios:7e4f4c933431bfd98a734e',
    messagingSenderId: '888433101003',
    projectId: 'employee-60bb8',
    storageBucket: 'employee-60bb8.appspot.com',
    iosBundleId: 'com.example.employee.RunnerTests',
  );
}
